<?php

namespace AppBundle\Repository;

/**
 * BoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoneRepository extends \Doctrine\ORM\EntityRepository
{
}
