<?php

namespace AppBundle\Repository;

/**
 * BoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBones()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select(
                'b.id',
                'b.name',
                'b.latin',
                'b.type',
                'b.summary',
                'b.description',
                'b.visible',
                'b.image',
                'b.xcoord',
                'b.ycoord',
                'b.topcoord',
                'b.leftcoord'
            )
            ->from('AppBundle:Bone', 'b')
            ->getQuery();

        return $query->getArrayResult();
    }

    /**
     * @param $id
     * @return array
     */
    public function getBone($id)
    {
         $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select(
                'b.name',
                'b.latin',
                'b.type',
                'b.description',
                'b.image'
            )
            ->from('AppBundle:Bone', 'b')
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
