<?php

namespace AppBundle\Repository;

/**
 * BoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBones()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('b.id',
                     'b.name',
                     'b.description',
                     'b.image',
                     'b.xcoord',
                     'b.ycoord')
            ->from('AppBundle:Bone', 'b')
            ->getQuery()
        ;
        return $query->getArrayResult();
    }
}
